// CrossGen: Mesh3Dto2Dfacesgmsh
// Main program: load a .step/.stp CAD file, identify planar faces,
// transform each to the [-1,1]^2 unit square on the XY plane,
// mesh with h = 2/np, and save each face as a separate .obj file.

#include <gmsh.h>
#include <iostream>
#include <string>
#include <vector>
#include <utility>
#include <filesystem>
#include <unordered_map>
#include <fstream>
#include <iomanip>
#include <cmath>
#include <cstdio>
#include <algorithm>
#include <sstream>

namespace fs = std::filesystem;

// --------------------------------------------------------------------------
// Write the current Gmsh mesh (2D elements only) to an OBJ file.
// Nodes are transformed from 3D model coords into the local 2D frame and
// then normalised to [-1,1]^2 before writing.
// --------------------------------------------------------------------------
static void writeOBJ(const std::string &path,
                     const std::vector<std::size_t> &nodeTags,
                     const std::vector<double> &nodeCoords)
{
    std::unordered_map<std::size_t, int> idx;
    idx.reserve(nodeTags.size());
    for (std::size_t i = 0; i < nodeTags.size(); ++i)
        idx[nodeTags[i]] = static_cast<int>(i + 1);

    std::ofstream out(path);
    if (!out)
        throw std::runtime_error("Failed to open OBJ file for writing: " + path);
    out.setf(std::ios::fixed, std::ios::floatfield);
    out << std::setprecision(17);
    out << "# OBJ generated by CrossGen Mesh3Dto2Dfacesgmsh\n";

    for (std::size_t i = 0; i < nodeTags.size(); ++i) {
        double x = nodeCoords[3 * i + 0];
        double y = nodeCoords[3 * i + 1];
        double z = nodeCoords[3 * i + 2];
        out << "v " << x << ' ' << y << ' ' << z << '\n';
    }

    // Fetch 2D elements
    std::vector<int> types;
    std::vector<std::vector<std::size_t>> elementTags, elementNodeTags;
    gmsh::model::mesh::getElements(types, elementTags, elementNodeTags, 2, -1);

    for (std::size_t k = 0; k < types.size(); ++k) {
        int et = types[k];
        const auto &nodes = elementNodeTags[k];
        if (et == 2) { // 3-node triangles
            for (std::size_t j = 0; j + 2 < nodes.size(); j += 3)
                out << "f " << idx[nodes[j]] << ' '
                    << idx[nodes[j + 1]] << ' '
                    << idx[nodes[j + 2]] << '\n';
        } else if (et == 9) { // 6-node triangles – corners only
            for (std::size_t j = 0; j + 5 < nodes.size(); j += 6)
                out << "f " << idx[nodes[j]] << ' '
                    << idx[nodes[j + 1]] << ' '
                    << idx[nodes[j + 2]] << '\n';
        } else if (et == 3) { // 4-node quads – split
            for (std::size_t j = 0; j + 3 < nodes.size(); j += 4) {
                out << "f " << idx[nodes[j]] << ' '
                    << idx[nodes[j + 1]] << ' '
                    << idx[nodes[j + 2]] << '\n';
                out << "f " << idx[nodes[j]] << ' '
                    << idx[nodes[j + 2]] << ' '
                    << idx[nodes[j + 3]] << '\n';
            }
        }
    }
    out.close();
}

// --------------------------------------------------------------------------
// Helper: 3-component vector ops
// --------------------------------------------------------------------------
struct Vec3 { double x, y, z; };

static Vec3 cross(const Vec3 &a, const Vec3 &b) {
    return {a.y * b.z - a.z * b.y,
            a.z * b.x - a.x * b.z,
            a.x * b.y - a.y * b.x};
}
static double dot(const Vec3 &a, const Vec3 &b) {
    return a.x * b.x + a.y * b.y + a.z * b.z;
}
static double length(const Vec3 &v) { return std::sqrt(dot(v, v)); }
static Vec3 normalise(const Vec3 &v) {
    double l = length(v);
    return {v.x / l, v.y / l, v.z / l};
}

// --------------------------------------------------------------------------
// Determine whether a Gmsh surface (dim=2) entity is planar.
// We sample a grid of normals via gmsh::model::getNormal and check that
// they are all (nearly) identical.
// Returns true and fills `normal` and `origin` if planar.
// --------------------------------------------------------------------------
static bool isPlanarFace(int surfaceTag, Vec3 &normal, Vec3 &origin) {
    // Get parametric bounds of the surface
    std::vector<double> pmin, pmax;
    gmsh::model::getParametrizationBounds(2, surfaceTag, pmin, pmax);
    double umin = pmin[0], vmin = pmin[1];
    double umax = pmax[0], vmax = pmax[1];

    // Sample normals on a small grid
    const int N = 4;
    std::vector<double> params;
    for (int i = 0; i <= N; ++i)
        for (int j = 0; j <= N; ++j) {
            double u = umin + (umax - umin) * i / N;
            double v = vmin + (vmax - vmin) * j / N;
            params.push_back(u);
            params.push_back(v);
        }

    std::vector<double> normals;
    gmsh::model::getNormal(surfaceTag, params, normals);

    // Reference normal from first sample
    Vec3 n0 = {normals[0], normals[1], normals[2]};
    double tol = 1e-6;
    for (std::size_t i = 3; i < normals.size(); i += 3) {
        Vec3 ni = {normals[i], normals[i + 1], normals[i + 2]};
        Vec3 diff = {ni.x - n0.x, ni.y - n0.y, ni.z - n0.z};
        if (length(diff) > tol)
            return false;
    }

    normal = normalise(n0);

    // Evaluate a point on the surface to serve as the origin of the local frame
    std::vector<double> p0params = {params[0], params[1]};
    std::vector<double> p0coords;
    gmsh::model::getValue(2, surfaceTag, p0params, p0coords);
    origin = {p0coords[0], p0coords[1], p0coords[2]};

    return true;
}

// --------------------------------------------------------------------------
// Determine whether a planar face has a "simple" boundary – i.e. the kind
// of face we want to skip (rectangles, circles, half-disks, etc.).
//
// Heuristic: get the boundary curves and query each curve's geometric type.
// A face is considered simple if ALL boundary edges are elementary analytic
// curves (Line, Circle, Ellipse) AND there are at most `maxEdges` of them.
// --------------------------------------------------------------------------
static bool isSimpleFace(int surfaceTag, int maxEdges = 4) {
    gmsh::vectorpair input = {{2, surfaceTag}};
    gmsh::vectorpair boundary;
    gmsh::model::getBoundary(input, boundary, /*combined=*/false,
                             /*oriented=*/false, /*recursive=*/false);

    int nEdges = 0;
    for (auto &[dim, tag] : boundary) {
        if (dim != 1) continue; // only look at curves
        ++nEdges;
        std::string etype;
        gmsh::model::getType(dim, tag, etype);
        // BSpline, Unknown, or other non-analytic curves → not simple
        if (etype != "Line" && etype != "Circle" && etype != "Ellipse")
            return false;
    }

    return nEdges <= maxEdges;
}

// --------------------------------------------------------------------------
// Build an orthonormal frame (e1, e2) in the plane with given normal.
// --------------------------------------------------------------------------
static void buildLocalFrame(const Vec3 &n, Vec3 &e1, Vec3 &e2) {
    // Pick a vector not parallel to n
    Vec3 up = (std::fabs(n.z) < 0.9) ? Vec3{0, 0, 1} : Vec3{1, 0, 0};
    e1 = normalise(cross(n, up));
    e2 = normalise(cross(n, e1));
}

// --------------------------------------------------------------------------
int main(int argc, char **argv) {
    if (argc < 5) {
        std::cerr << "Usage: Mesh3Dto2Dfacesgmsh <input.step> <output_fmt> <start_id> <np> [--prune]\n"
                  << "  output_fmt: printf-style path with %%d, e.g. geom_%%d.obj\n"
                  << "  --prune:    skip simple faces (rectangles, circles, half-disks, etc.)\n";
        return 1;
    }

    const std::string inputStep = argv[1];
    const std::string outputFmt = argv[2]; // e.g. "outdir/geom_%d.obj"
    const int startId = std::stoi(argv[3]);
    const int np = std::stoi(argv[4]);

    bool pruneSimple = false;
    for (int i = 5; i < argc; ++i) {
        if (std::string(argv[i]) == "--prune")
            pruneSimple = true;
    }
    if (np <= 0) {
        std::cerr << "Error: np must be a positive integer.\n";
        return 1;
    }

    try {
        gmsh::initialize();
        gmsh::option::setNumber("General.Terminal", 1);

        // Load STEP file via the OCC kernel
        gmsh::open(inputStep);
        gmsh::model::occ::synchronize();

        // Enumerate all surface (dim=2) entities
        std::vector<std::pair<int, int>> surfaces;
        gmsh::model::getEntities(surfaces, 2);

        std::cout << "Found " << surfaces.size() << " surface(s) in STEP file.\n";

        // Collect planar faces (optionally pruning simple ones)
        struct PlanarFace {
            int tag;
            Vec3 normal;
            Vec3 origin;
        };
        std::vector<PlanarFace> planarFaces;
        int skippedSimple = 0;
        for (auto &[dim, tag] : surfaces) {
            Vec3 n{}, o{};
            if (isPlanarFace(tag, n, o)) {
                if (pruneSimple && isSimpleFace(tag)) {
                    ++skippedSimple;
                    continue;
                }
                planarFaces.push_back({tag, n, o});
            }
        }

        std::cout << "Identified " << planarFaces.size()
                  << " planar face(s)";
        if (pruneSimple)
            std::cout << " (" << skippedSimple << " simple face(s) pruned)";
        std::cout << ".\n";

        if (planarFaces.empty()) {
            std::cerr << "No planar faces found – nothing to mesh.\n";
            gmsh::finalize();
            return 0;
        }

        fs::path fmtPath(outputFmt);
        if (fmtPath.has_parent_path())
            fs::create_directories(fmtPath.parent_path());

        const double h = 2.0 / static_cast<double>(np);
        int faceIndex = startId;

        for (auto &face : planarFaces) {
            // ---- Build a fresh model for this face ----
            // Re-open the STEP so that we get a clean copy each time
            std::string modelName = "face_" + std::to_string(faceIndex);
            gmsh::model::add(modelName);
            gmsh::model::setCurrent(modelName);

            gmsh::open(inputStep);
            gmsh::model::occ::synchronize();

            // Remove every surface except the one we want
            std::vector<std::pair<int, int>> allEnts;
            gmsh::model::getEntities(allEnts);

            // We must remove higher-dimensional entities first (3D volumes)
            // so that the surfaces are freed, then remove unwanted surfaces.
            // Remove all 3D entities
            {
                std::vector<std::pair<int, int>> vols;
                gmsh::model::getEntities(vols, 3);
                if (!vols.empty())
                    gmsh::model::occ::remove(vols, false);
                gmsh::model::occ::synchronize();
            }

            // Now remove all surfaces except the target face
            {
                std::vector<std::pair<int, int>> surfs;
                gmsh::model::getEntities(surfs, 2);
                std::vector<std::pair<int, int>> toRemove;
                for (auto &[d, t] : surfs) {
                    if (t != face.tag)
                        toRemove.push_back({d, t});
                }
                if (!toRemove.empty())
                    gmsh::model::occ::remove(toRemove, false);
                gmsh::model::occ::synchronize();
            }

            // Build local 2D frame on the plane
            Vec3 e1{}, e2{};
            buildLocalFrame(face.normal, e1, e2);

            // ---- Retrieve boundary nodes of the remaining face to find extent ----
            // We need to know the 2D extent to normalise.  First, get the
            // bounding box in 3D, project corners into local frame.
            double bxmin, bymin, bzmin, bxmax, bymax, bzmax;
            gmsh::model::getBoundingBox(2, face.tag,
                                        bxmin, bymin, bzmin,
                                        bxmax, bymax, bzmax);

            // Project the 8 corners of the 3D bbox into local (u,v)
            double uMin = 1e30, uMax = -1e30, vMin = 1e30, vMax = -1e30;
            for (int ci = 0; ci < 8; ++ci) {
                double cx = (ci & 1) ? bxmax : bxmin;
                double cy = (ci & 2) ? bymax : bymin;
                double cz = (ci & 4) ? bzmax : bzmin;
                Vec3 d = {cx - face.origin.x,
                          cy - face.origin.y,
                          cz - face.origin.z};
                double u = dot(d, e1);
                double v = dot(d, e2);
                uMin = std::min(uMin, u);
                uMax = std::max(uMax, u);
                vMin = std::min(vMin, v);
                vMax = std::max(vMax, v);
            }

            double width  = uMax - uMin;
            double height = vMax - vMin;
            double maxDim = std::max(width, height);
            if (maxDim <= 0) { ++faceIndex; continue; }

            double cx = 0.5 * (uMin + uMax);
            double cy_local = 0.5 * (vMin + vMax);
            double s = 2.0 / maxDim;

            // Build an affine transform that maps the 3D planar face
            // into [-1,1]^2 on the z=0 plane.
            //
            // For a point P in 3D on the plane:
            //   d = P - origin
            //   u = dot(d, e1),  v = dot(d, e2)
            //   u' = s*(u - cx),  v' = s*(v - cy_local)
            //   P' = (u', v', 0)
            //
            // Gmsh's affine transform is a 4x4 matrix stored row-major
            // (last row implicitly 0 0 0 1).
            // P' = A * (P - origin) means we need:
            //   row0 = s*e1  with translation accounting for centering
            //   row1 = s*e2
            //   row2 = 0

            // Gmsh expects the 4x4 as 16 doubles (row-major, last row omitted
            // when using affineTransform, but the API takes all 16 anyway).
            // The transform is:  P' = M * P + T
            // M = s * [e1 ; e2 ; 0]   (rows are e1, e2, zero)
            // T = -s * [dot(origin,e1)+cx ; dot(origin,e2)+cy_local ; 0] ...
            // but we use the Gmsh OCC affine transform which takes
            // (a11..a33, t1, t2, t3) as a 4×3 column-major or 3×4 row-major.

            // Actually, gmsh::model::occ::affineTransform takes a flat 16-entry
            // 4×4 row-major matrix applied as X' = A * X.
            // Row 0: s*e1.x  s*e1.y  s*e1.z  tx
            // Row 1: s*e2.x  s*e2.y  s*e2.z  ty
            // Row 2: 0       0       0        0
            // Row 3: 0       0       0        1
            // where tx = -s*(dot(origin,e1) + cx)
            //       ty = -s*(dot(origin,e2) + cy_local)

            double oU = dot({face.origin.x, face.origin.y, face.origin.z}, e1);
            double oV = dot({face.origin.x, face.origin.y, face.origin.z}, e2);
            double tx = -s * (oU) + (-s * cx + s * oU);  // simplifies to -s*cx
            // Let's be precise:
            //   u' = s*(dot(P, e1) - dot(origin, e1) - cx)
            //      = s*dot(P, e1) - s*(oU + cx)
            //   so row0 = [s*e1.x, s*e1.y, s*e1.z, -s*(oU + cx)]
            tx = -s * (oU + cx);
            double ty = -s * (oV + cy_local);

            std::vector<double> A = {
                s * e1.x, s * e1.y, s * e1.z, tx,
                s * e2.x, s * e2.y, s * e2.z, ty,
                0,        0,        0,         0,
                0,        0,        0,         1
            };

            // Apply the affine transform to all remaining entities
            std::vector<std::pair<int, int>> remaining;
            gmsh::model::getEntities(remaining);
            if (!remaining.empty())
                gmsh::model::occ::affineTransform(remaining, A);
            gmsh::model::occ::synchronize();

            // Set uniform mesh size
            std::vector<std::pair<int, int>> points;
            gmsh::model::getEntities(points, 0);
            if (!points.empty())
                gmsh::model::mesh::setSize(points, h);

            // Generate 2D mesh
            gmsh::model::mesh::generate(2);

            // Retrieve nodes and write OBJ
            std::vector<std::size_t> nodeTags;
            std::vector<double> nodeCoords, nodeParam;
            gmsh::model::mesh::getNodes(nodeTags, nodeCoords, nodeParam);

            // Build output path using printf-style format
            char buf[1024];
            std::snprintf(buf, sizeof(buf), outputFmt.c_str(), faceIndex);
            std::string outPath(buf);
            writeOBJ(outPath, nodeTags, nodeCoords);

            std::cout << "  Face " << faceIndex
                      << " (surface tag " << face.tag
                      << ") -> " << outPath << '\n';

            gmsh::model::remove();
            ++faceIndex;
        }

        gmsh::finalize();
        std::cout << "Done. Wrote " << (faceIndex - startId)
                  << " planar face mesh(es).\n";

    } catch (const std::exception &e) {
        std::cerr << "Error: " << e.what() << "\n";
        try { gmsh::finalize(); } catch (...) {}
        return 1;
    } catch (...) {
        std::cerr << "Unknown error.\n";
        try { gmsh::finalize(); } catch (...) {}
        return 1;
    }

    return 0;
}
