// Test separatrix tracing from cross field singularities.
// Outputs traced separatrices as an OBJ file for visualization.

#include <iostream>
#include <fstream>
#include <memory>
#include <string>
#include <cmath>

#include "mesh/Mesh.hxx"
#include "crossfield/CrossField.hxx"
#include "tracing_1/SeparatrixTrace.hxx"

// Write separatrices to an OBJ file as polylines
bool writeSeparatricesToOBJ(const std::string& path, const SeparatrixTrace& trace) {
    std::ofstream out(path);
    if (!out.is_open()) {
        std::cerr << "Failed to open file for writing: " << path << "\n";
        return false;
    }
    
    out << "# Separatrix trace output\n";
    out << "# Generated by TestTrace\n";
    out << "# Number of separatrices: " << trace.separatrices.size() << "\n\n";
    
    // First pass: write all vertices
    int vertexOffset = 1; // OBJ indices are 1-based
    std::vector<std::pair<int, int>> lineRanges; // (start_vertex, end_vertex) for each separatrix
    
    for (const auto& sep : trace.separatrices) {
        int startIdx = vertexOffset;
        
        for (const auto& pt : sep.path) {
            // Write vertex (x, y, z=0 for 2D)
            out << "v " << pt.global_pos[0] << " " << pt.global_pos[1] << " 0\n";
            vertexOffset++;
        }
        
        int endIdx = vertexOffset - 1;
        if (endIdx >= startIdx) {
            lineRanges.push_back({startIdx, endIdx});
        }
    }
    
    out << "\n# Separatrix polylines\n";
    
    // Second pass: write line segments for each separatrix
    int sepIdx = 0;
    for (const auto& [startIdx, endIdx] : lineRanges) {
        const auto& sep = trace.separatrices[sepIdx];
        
        // Write comment with separatrix info
        out << "# Separatrix " << sep.id 
            << " (origin singularity: " << sep.origin_singularity_id
            << ", points: " << sep.path.size()
            << ", reason: ";
        
        switch (sep.termination_reason) {
            case TerminationReason::RUNNING: out << "RUNNING"; break;
            case TerminationReason::HIT_BOUNDARY: out << "HIT_BOUNDARY"; break;
            case TerminationReason::SELF_INTERSECTION: out << "SELF_INTERSECTION"; break;
            case TerminationReason::SINGULARITY_CUTOFF: out << "SINGULARITY_CUTOFF"; break;
            case TerminationReason::MAX_STEPS_REACHED: out << "MAX_STEPS_REACHED"; break;
            case TerminationReason::MERGED_TANGENTIAL: out << "MERGED_TANGENTIAL (with " << sep.merged_with_id << ")"; break;
            case TerminationReason::LIMIT_CYCLE: out << "LIMIT_CYCLE"; break;
            case TerminationReason::REPEATED_CROSSING: out << "REPEATED_CROSSING"; break;
        }
        out << ")\n";
        
        // Write polyline using 'l' command
        out << "l";
        for (int i = startIdx; i <= endIdx; ++i) {
            out << " " << i;
        }
        out << "\n";
        
        sepIdx++;
    }
    
    out.close();
    return true;
}

// Print summary of tracing results
void printTraceSummary(const SeparatrixTrace& trace) {
    int totalPoints = 0;
    int hitBoundary = 0;
    int selfIntersect = 0;
    int singularityCutoff = 0;
    int maxSteps = 0;
    int stillRunning = 0;
    int mergedTangential = 0;
    int limitCycle = 0;
    int repeatedCrossing = 0;
    
    for (const auto& sep : trace.separatrices) {
        totalPoints += sep.path.size();
        
        switch (sep.termination_reason) {
            case TerminationReason::RUNNING: stillRunning++; break;
            case TerminationReason::HIT_BOUNDARY: hitBoundary++; break;
            case TerminationReason::SELF_INTERSECTION: selfIntersect++; break;
            case TerminationReason::SINGULARITY_CUTOFF: singularityCutoff++; break;
            case TerminationReason::MAX_STEPS_REACHED: maxSteps++; break;
            case TerminationReason::MERGED_TANGENTIAL: mergedTangential++; break;
            case TerminationReason::LIMIT_CYCLE: limitCycle++; break;
            case TerminationReason::REPEATED_CROSSING: repeatedCrossing++; break;
        }
    }
    
    std::cout << "\n=== Tracing Summary ===\n";
    std::cout << "Total separatrices: " << trace.separatrices.size() << "\n";
    std::cout << "Total trace points: " << totalPoints << "\n";
    std::cout << "Average points per separatrix: " 
              << (trace.separatrices.empty() ? 0 : totalPoints / trace.separatrices.size()) << "\n";
    std::cout << "\nTermination reasons:\n";
    std::cout << "  Hit boundary:        " << hitBoundary << "\n";
    std::cout << "  Self-intersection:   " << selfIntersect << "\n";
    std::cout << "  Singularity cutoff:  " << singularityCutoff << "\n";
    std::cout << "  Merged tangential:   " << mergedTangential << "\n";
    std::cout << "  Limit cycle:         " << limitCycle << "\n";
    std::cout << "  Repeated crossing:   " << repeatedCrossing << "\n";
    std::cout << "  Max steps reached:   " << maxSteps << "\n";
    std::cout << "  Still running:       " << stillRunning << "\n";
}

int main(int argc, char** argv) {
    if (argc < 2) {
        std::cerr << "Usage: " << argv[0] << " <mesh.obj> [options]\n";
        std::cerr << "Options:\n";
        std::cerr << "  --out <file.obj>     Write separatrices to OBJ file (default: separatrices.obj)\n";
        std::cerr << "  --iterations N       MBO iterations (default: 100)\n";
        std::cerr << "  --verbose            Print detailed progress\n";
        return 1;
    }
    
    const std::string meshPath = argv[1];
    std::string outputPath = "separatrices.obj";
    int mboIterations = 100;
    bool verbose = false;
    
    // Parse arguments
    for (int i = 2; i < argc; ++i) {
        std::string arg = argv[i];
        if (arg == "--out" && i + 1 < argc) {
            outputPath = argv[++i];
        } else if (arg == "--iterations" && i + 1 < argc) {
            mboIterations = std::stoi(argv[++i]);
        } else if (arg == "--verbose") {
            verbose = true;
        }
    }
    
    try {
        // Load mesh
        std::cout << "Loading mesh: " << meshPath << "\n";
        auto mesh = std::make_shared<Mesh>(meshPath);
        std::cout << "  Vertices: " << mesh->vertices.size() << "\n";
        std::cout << "  Triangles: " << mesh->triangles.size() << "\n";
        
        // Create cross field and run MBO
        std::cout << "\n--- Cross Field (MBO Method) ---\n";
        auto crossField = std::make_shared<CrossField>(mesh, mboIterations);
        
        // Initialize with random field
        crossField->initialize(1); // method 1 = random initialization
        
        // Run MBO iterations
        std::cout << "Running MBO optimization...\n";
        crossField->runMBO();
        
        // Compute singularities
        crossField->computeSingularities();
        std::cout << "Detected singularities: " << crossField->singularTriangles.size() << "\n";
        
        if (verbose) {
            for (const auto& [triIdx, index] : crossField->singularTriangles) {
                std::cout << "  Triangle " << triIdx << ": index = " << index << "\n";
            }
        }
        
        if (crossField->singularTriangles.empty()) {
            std::cout << "\033[33m[WARNING]\033[0m No singularities found. No separatrices to trace.\n";
            return 0;
        }
        
        // Initialize and trace separatrices
        std::cout << "\n--- Separatrix Tracing ---\n";
        SeparatrixTrace trace(crossField);
        
        std::cout << "Initializing separatrices from singularities...\n";
        trace.initializeSeparatrices();
        std::cout << "Initialized " << trace.separatrices.size() << " separatrices\n";
        
        std::cout << "Tracing separatrices...\n";
        trace.trace();
        
        // Print summary
        printTraceSummary(trace);
        
        // Write output
        std::cout << "\n--- Output ---\n";
        if (writeSeparatricesToOBJ(outputPath, trace)) {
            std::cout << "\033[32m[SUCCESS]\033[0m Wrote separatrices to: " << outputPath << "\n";
        } else {
            std::cerr << "\033[31m[ERROR]\033[0m Failed to write output file\n";
            return 2;
        }
        
        return 0;
        
    } catch (const std::exception& e) {
        std::cerr << "\033[31m[ERROR]\033[0m " << e.what() << "\n";
        return 3;
    }
}
